****** Pokémon Trading Card Game Deck List ******

##Pokémon - 25

* 2 Buneary BCR 116
* 2 Indeedee SHF 56
* 1 Miltank FLF 83
* 2 Minccino SSH 146
* 1 Snorlax BKT 118
* 1 Stufful RCL 149
* 2 Zigzagoon PRC 111
* 1 Cinccino SSH 147
* 1 Linoone PRC 112
* 1 Lopunny BCR 117
* 4 Ralts PLS 59
* 3 Kirlia LTR 124
* 1 Kirlia CRE 60
* 2 Gallade PLS 61
* 1 Gardevoir CRE 61

##Trainer Cards - 22

* 4 Energy Retrieval SSH 160
* 1 Professor's Letter BKT 146
* 1 Avery CRE 130
* 1 Fisherman BKT 136
* 3 Healing Scarf ROS 84
* 3 Pokémon Center Lady FLF 93
* 2 Poké Ball KSS 35
* 2 Colress PLS 118
* 3 Hop SSH 165
* 1 Fog Crystal CRE 140
* 1 Cilan NXD 86

##Energy - 13

* 13 Psychic Energy SWSHEnergy 5

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******